### ISSUE TITLE
TypeError: mime.lookup is not a function error

### ISSUE THREAD

**Issue by simonecogno** [theycallmeswift/node-mongodb-s3-backup#28]
I get this error after running ` mongodb_s3_backup -n config.sample.json`.
Do you know what can cause this?

```
/usr/lib/node_modules/mongodb_s3_backup/index.js:262
        throw(err);
        ^

TypeError: mime.lookup is not a function
    at /usr/lib/node_modules/mongodb_s3_backup/node_modules/knox/lib/client.js:386:28
    at FSReqWrap.oncomplete (fs.js:82:15)

```

**Comment by bbqaaq** [comment]
I've encounter this issue too, seems the problem is from knox, which is the s3 library used by this library.

Quick fix is replacing the package.json and redirect to the temporary fix link:

ref: https://github.com/Automattic/knox/issues/326

**Comment by dkoo761** [comment]
I've forked this repo to fix this issue, remove a deprecated warning, fix logging and add support for: replica sets, SSL, and authenticationDatabase options. Feel free to use it if you like: https://github.com/dkoo761/node-mongodb-s3-backup.

NOTE: My fork is not published to NPM so you'll need to download and install it (which is easy and I've added instructions in the README).
